//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Footer
    {
        public int Id { get; set; }
        public string C_Name { get; set; }
        public string C_Description { get; set; }
        public string C_Image { get; set; }
        public string C_Link { get; set; }
        public string C_Alt { get; set; }
        public string C_Title { get; set; }
        public string C_Display { get; set; }
    }
}
