//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Images
    {
        public C_Images()
        {
            this.C_Section_Content = new HashSet<C_Section_Content>();
            this.C_Section_Content1 = new HashSet<C_Section_Content>();
            this.C_Section_Content2 = new HashSet<C_Section_Content>();
            this.C_Section_Content3 = new HashSet<C_Section_Content>();
            this.C_Section_Content4 = new HashSet<C_Section_Content>();
            this.C_Section_Content5 = new HashSet<C_Section_Content>();
            this.C_Section_Content6 = new HashSet<C_Section_Content>();
            this.C_Section_Content7 = new HashSet<C_Section_Content>();
        }
    
        public int Id { get; set; }
        [Required]
        public string C_Title { get; set; }
        public string C_Alt { get; set; }
        public Nullable<int> C_Width { get; set; }
        public Nullable<int> C_Hight { get; set; }
        [Required]
        public string C_Link { get; set; }
        public string C_Description { get; set; }
        public Nullable<int> C_Order { get; set; }
        public string C_Display { get; set; }
        [Required]
        public Nullable<int> C_Section_Id { get; set; }
    
        public virtual ICollection<C_Section_Content> C_Section_Content { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content1 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content2 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content3 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content4 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content5 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content6 { get; set; }
        public virtual ICollection<C_Section_Content> C_Section_Content7 { get; set; }
    }
}
