//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Menu
    {
        public int Id { get; set; }
        public string C_String___String___String___String { get; set; }
        public string C_Link { get; set; }
        public string C_Li { get; set; }
        public string C_Title { get; set; }
        public string C_Img { get; set; }
        public string C_ToolTip { get; set; }
        public Nullable<int> C_Main_Id { get; set; }
        public string C_Has_sub { get; set; }
        public string C_Display { get; set; }
        public string C_Alt { get; set; }
        public string C_Pro_Ico { get; set; }
    }
}
