//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Section_Table
    {
        public C_Section_Table()
        {
            this.C_Section_Content = new HashSet<C_Section_Content>();
        }
    
        public int Id { get; set; }
        public string C_Section_Name { get; set; }
        public string C_Section_Image { get; set; }
        public string C_Heading { get; set; }
        public string C_Sub_Heading { get; set; }
        public string C_Main_Txt_1 { get; set; }
        public string C_Main_Txt_2 { get; set; }
        public string C_Main_Txt_3 { get; set; }
        public string C_Main_Txt_4 { get; set; }
        public string C_Main_Txt_5 { get; set; }
        public string C_Main_Img_1 { get; set; }
        public string C_Main_Img_2 { get; set; }
        public string C_Main_Img_3 { get; set; }
        public string C_Main_Img_4 { get; set; }
        public string C_Display { get; set; }
        [Required]
        public Nullable<int> C_Order { get; set; }
    
        public virtual ICollection<C_Section_Content> C_Section_Content { get; set; }
        public virtual C_Section_Table C_Section_Table1 { get; set; }
        public virtual C_Section_Table C_Section_Table2 { get; set; }
    }
}
