//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Section_Content
    {
        public int Id { get; set; }
        public int C_Section_Id { get; set; }
        public string C_Heading { get; set; }
        public string C_Sub_Heading { get; set; }
        public string C_H1_txt1 { get; set; }
        public string C_H1_txt2 { get; set; }
        public string C_H2_txt1 { get; set; }
        public string C_H2_txt2 { get; set; }
        public string C_H3_txt1 { get; set; }
        public string C_H3_txt2 { get; set; }
        public string C_H4_txt1 { get; set; }
        public string C_H4_txt2 { get; set; }
        public string C_p_txt1 { get; set; }
        public string C_p_txt2 { get; set; }
        public string C_p_txt3 { get; set; }
        public string C_p_txt4 { get; set; }
        public string C_R_To_L { get; set; }
        public string C_L_To_R { get; set; }
        public string C_So_Page_Name { get; set; }
        public string C_So_Page_Link { get; set; }
        public string C_So_Video_Link { get; set; }
        public string C_So_Access_Token { get; set; }
        public string C_So_Photo_Album { get; set; }
        public string C_So_Search_Trim_1 { get; set; }
        public string C_So_Search_Trim_2 { get; set; }
        public string C_Txt_1 { get; set; }
        public string C_Txt_2 { get; set; }
        public string C_Txt_3 { get; set; }
        public string C_Txt_4 { get; set; }
        public string C_Txt_5 { get; set; }
        public string C_Txt_6 { get; set; }
        public string C_Txt_7 { get; set; }
        public string C_Txt_8 { get; set; }
        public string C_Url_1 { get; set; }
        public string C_Url_2 { get; set; }
        public string C_Url_3 { get; set; }
        public string C_Url_4 { get; set; }
        public string C_Url_5 { get; set; }
        public string C_Url_6 { get; set; }
        public string C_Url_7 { get; set; }
        public string C_Url_8 { get; set; }
        public Nullable<int> C_Img_1 { get; set; }
        public Nullable<int> C_Img_2 { get; set; }
        public Nullable<int> C_Img_3 { get; set; }
        public Nullable<int> C_Img_4 { get; set; }
        public Nullable<int> C_Img_5 { get; set; }
        public Nullable<int> C_Img_6 { get; set; }
        public Nullable<int> C_Img_7 { get; set; }
        public Nullable<int> C_Img_8 { get; set; }
        public string C_Description { get; set; }
        public Nullable<int> C_Order { get; set; }
    
        public virtual C_Images C_Images { get; set; }
        public virtual C_Images C_Images1 { get; set; }
        public virtual C_Images C_Images2 { get; set; }
        public virtual C_Images C_Images3 { get; set; }
        public virtual C_Images C_Images4 { get; set; }
        public virtual C_Images C_Images5 { get; set; }
        public virtual C_Images C_Images6 { get; set; }
        public virtual C_Images C_Images7 { get; set; }
        public virtual C_Section_Table C_Section_Table { get; set; }
    }
}
