//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace Tamplate_1.Models
{
    
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShaddadDbEntities : DbContext
    {
        
        public ShaddadDbEntities()
            : base("name=ShaddadDbEntities")
        {   
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Footer> C_Footer { get; set; }
        public DbSet<C_Images> C_Images { get; set; }
        public DbSet<C_Menu> C_Menu { get; set; }
        public DbSet<C_Section_Content> C_Section_Content { get; set; }
        public DbSet<C_Section_Table> C_Section_Table { get; set; }
        public DbSet<Themes> Themes { get; set; }
    }
}
