//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamplate_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public int Id { get; set; }
        public string C_Color1 { get; set; }
        public string C_Color2 { get; set; }
        public string C_Color3 { get; set; }
        public string C_Color4 { get; set; }
        public string C_Color5 { get; set; }
        public string C_Color6 { get; set; }
    }
}
